### PR TITLE
Module maintainer guidelines ccoe 863

### PR DESCRIPTION
**Pull request by jsimoni**
# Description

added guidelines for module maintainers / repo admins

Fixes # n/a

# Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] My code follows the [style guidelines for Terraform](https://www.terraform.io/docs/configuration/style.html) ([terraform fmt](https://www.terraform.io/docs/commands/fmt.html) will enforce this at PR)
- [x] I have performed a self-review of my own code
- [x] I have [commented](https://www.terraform.io/docs/configuration/syntax.html#comments) my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes (PRs run a number of tests such as [terraform init](https://www.terraform.io/docs/commands/init.html), [terraform validate](https://www.terraform.io/docs/commands/validate.html), and [checkov](https://www.checkov.io/))
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jsimoni** [comment]
@Wayne-Ennis @rlenahan7 @ckilpatrick20 I created this as a draft pull request so you guys can provide feedback and @Wayne-Ennis can add the guidance on Topics (CCOE-923) in this branch if he wants.

Did I miss anything?

**Comment by ckilpatrick20** [comment]
> @Wayne-Ennis @rlenahan7 @ckilpatrick20 I created this as a draft pull request so you guys can provide feedback and @Wayne-Ennis can add the guidance on Topics (CCOE-923) in this branch if he wants.
> 
> Did I miss anything?

It looks pretty complete to me. It covers the basics of setting up and requesting a new repo. The only thing I'd add (not sure if this is a story already assigned to someone) would be that the new repo owner would have to specify in the actions files which directory the Terraform code lives in. Right now it is set to scan the root. The only Terraform command that can be run recursively is the fmt command.

**Comment by jsimoni** [comment]
> > @Wayne-Ennis @rlenahan7 @ckilpatrick20 I created this as a draft pull request so you guys can provide feedback and @Wayne-Ennis can add the guidance on Topics (CCOE-923) in this branch if he wants.
> > Did I miss anything?
> 
> It looks pretty complete to me. It covers the basics of setting up and requesting a new repo. The only thing I'd add (not sure if this is a story already assigned to someone) would be that the new repo owner would have to specify in the actions files which directory the Terraform code lives in. Right now it is set to scan the root. The only Terraform command that can be run recursively is the fmt command.

OK so a maintainer would need to modify the GitHub actions to scan any submodules if they repo was structured as we suggest... https://github.com/jsimoni-org/terraform-module-template/blob/module-maintainer-guidelines-CCOE-863/module-maintainer-guidelines.md#standard-module-structure (I'm not all that concerned about any examples.)

**Comment by jsimoni** [comment]
@ckilpatrick20 @Wayne-Ennis & I met & we agreed to wait to merge until after @Wayne-Ennis has added his content for CCOE-923 to this branch, but otherwise this looks good.

**Pull request merged**
