### PR TITLE
Ccoe 950

### PR DESCRIPTION
**Pull request by ckilpatrick20**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] My code follows the [style guidelines for Terraform](https://www.terraform.io/docs/configuration/style.html) ([terraform fmt](https://www.terraform.io/docs/commands/fmt.html) will enforce this at PR)
- [x] I have performed a self-review of my own code
- [ ] I have [commented](https://www.terraform.io/docs/configuration/syntax.html#comments) my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes (PRs run a number of tests such as [terraform init](https://www.terraform.io/docs/commands/init.html), [terraform validate](https://www.terraform.io/docs/commands/validate.html), and [checkov](https://www.checkov.io/))
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ckilpatrick20** [comment]
@jsimoni @rlenahan7 @Wayne-Ennis Good morning guys! Any chance I can get some feedback on this PR?

**Comment by jsimoni** [comment]
@ckilpatrick20 can you schedule a quick, 30 minute, call to review with you, me, @rlenahan7 & @Wayne-Ennis.  I think I'm OK with this PR, but would like to talk it through with the team in the spirit of collaboration.

**Comment by ckilpatrick20** [comment]
> @ckilpatrick20 can you schedule a quick, 30 minute, call to review with you, me, @rlenahan7 & @Wayne-Ennis. I think I'm OK with this PR, but would like to talk it through with the team in the spirit of collaboration.

Absolutely. I'll get something set up.

**Comment by ckilpatrick20** [comment]
@jsimoni @rlenahan7 @Wayne-Ennis Thanks for catching the spell check Jay. Also, I've made the requested changes to the release section in the module-maintainer-guidelines readme.

**Pull request merged**
